{
  "openapi": "3.0.1",
  "info": {
    "title": "DateTime Service",
    "description": "Сервис получения дат доступности и интервалов доставки/самовывоза. Версия 2.0 переписана на .Net и прямые обращения к SQL.",
    "termsOfService": "",
    "version": "2.0",
    "contact": {
      "name": "Андрей Бородавко",
      "email": "a.borodavko@21vek.by"
    }
  },
  "externalDocs": {
    "description": "Статья в базе знаний",
    "url": "https://aggregator.atlassian.net/wiki/spaces/SS/pages/2832695334/v2"
  },
  "servers": [
    {
      "url": "https://site.com/NetMS"
    }
  ],
  "tags": [
    {
      "name": "DateTime",
      "description": ""
    },
    {
      "name": "Authenticate",
      "description": ""
    }
  ],
  "paths": {
    "/api/DateTime/IntervalList": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "DateTime"
        ],
        "summary": "Получить интервалы доставки",
        "description": "Получает список доступных интервалов доставки",
        "requestBody": {
          "description": "содержимое отправляемого запроса",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/payload_interval"
              },
              "examples": {
                "Интервалы для курьерской доставки по коду адреса": {
                  "$ref": "#/components/examples/interval_courier"
                },
                "Интервалы для курьерской доставки по координатам": {
                  "$ref": "#/components/examples/interval_courier_coords"
                },
                "Интервалы для самовывоза с ПВЗ": {
                  "$ref": "#/components/examples/interval_self"
                },
                "Интервалы по имеющемуся заказу (Creatio)": {
                  "$ref": "#/components/examples/interval_byOrder"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "запрос выполнен",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "properties": {
                          "begin": {
                            "type": "string",
                            "format": "date-time",
                            "description": "Начало интервала"
                          },
                          "end": {
                            "type": "string",
                            "format": "date-time",
                            "description": "Конец интервала"
                          },
                          "bonus": {
                            "type": "string",
                            "format": "boolean",
                            "description": "Признак того, что за выбор этого интервала будет больше бонусов"
                          }
                        }
                      },
                      "example": [
                        {
                          "begin": "2021-03-23T19:00:00",
                          "end": "2021-03-23T21:00:00",
                          "bonus": true
                        },
                        {
                          "begin": "2021-03-23T21:00:00",
                          "end": "2021-03-23T23:00:00",
                          "bonus": false
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "некорректные входные данныу",
            "content": {}
          },
          "401": {
            "description": "Не аутентифицирован"
          },
          "403": {
            "description": "Отсутствуют права на данный эндпоинт"
          },
          "500": {
            "description": "внутренняя ошибка сервера",
            "content": {}
          }
        },
        "x-codegen-request-body-name": "body"
      }
    },
    "/api/DateTime/AvailableDeliveryTypes": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "DateTime"
        ],
        "summary": "Получить доступность видов доставки",
        "description": "Получает список доступных видов доставки",
        "requestBody": {
          "description": "содержимое отправляемого запроса",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/payload_availabledeliverytypes"
              },
              "examples": {
                "Доступные виды доставки": {
                  "$ref": "#/components/examples/available_delivery_types"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "запрос выполнен",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "courier": {
                      "type": "object",
                      "properties": {
                        "available": {
                          "type": "boolean"
                        }
                      }
                    },
                    "pickup_point": {
                      "type": "object",
                      "properties": {
                        "available": {
                          "type": "boolean"
                        }
                      }
                    },
                    "interval": {
                      "type": "object",
                      "properties": {
                        "available": {
                          "type": "boolean"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "courier": {
                    "available": true
                  },
                  "pickup_point": {
                    "available": true
                  },
                  "interval": {
                    "available": true
                  }
                }
              }
            }
          },
          "400": {
            "description": "некорректные входные данные",
            "content": {}
          },
          "401": {
            "description": "Не аутентифицирован"
          },
          "403": {
            "description": "Отсутствуют права на данный эндпоинт"
          },
          "500": {
            "description": "внутренняя ошибка сервера",
            "content": {}
          }
        },
        "x-codegen-request-body-name": "body"
      }
    },
    "/api/DateTime/AvailableDate": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "DateTime"
        ],
        "summary": "Получить даты доступности",
        "description": "Получает ближайшие доступные даты доставки и самовывоза по каждому товару",
        "requestBody": {
          "description": "содержимое отправляемого запроса",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/payload_availabledate"
              },
              "examples": {
                "Даты доступности без учета количества (листинг и т.д.)": {
                  "$ref": "#/components/examples/availabledate_basic"
                },
                "Даты доступности с учетом количества (корзина)": {
                  "$ref": "#/components/examples/availabledate_quantity"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "запрос выполнен",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "data": {
                      "type": "object",
                      "additionalProperties": {
                        "type": "object",
                        "description": "Ключ - артикул",
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Артикул"
                          },
                          "sales_code": {
                            "type": "string",
                            "description": "Код уценки"
                          },
                          "courier": {
                            "type": "string",
                            "format": "date-time",
                            "description": "Дата курьерской доставки"
                          },
                          "self": {
                            "type": "string",
                            "format": "date-time",
                            "description": "Дата самовывоза"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "data": {
                    "101937": {
                      "code": "101937",
                      "courier": "2021-03-23T00:00:00",
                      "self": "2021-03-24T00:00:00"
                    },
                    "1020938": {
                      "code": "1020938",
                      "courier": "2021-03-24T00:00:00",
                      "self": "2021-03-24T00:00:00"
                    },
                    "789734_2242670": {
                      "code": "789734",
                      "sales_code": "2242670",
                      "courier": "2021-05-05T00:00:00",
                      "self": "2021-05-06T00:00:00"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "некорректные входные данныу",
            "content": {}
          },
          "401": {
            "description": "Не аутентифицирован"
          },
          "403": {
            "description": "Отсутствуют права на данный эндпоинт"
          },
          "500": {
            "description": "внутренняя ошибка сервера",
            "content": {}
          }
        }
      }
    },
    "/api/Authenticate/login": {
      "post": {
        "tags": [
          "Authenticate"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/LoginModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Удачная аутентификация, возвращается токен",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string",
                      "description": "Токен аутентификации для помещения в заголовок Authorization",
                      "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5AdGVzdC5jb20iLCJqdGkiOiJiZGY1MThlZC05MDg2LTQ2YmMtOGE5My1jNjNmMjgyMjVkMGQiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTYxNjU5MTk1NSwiaXNzIjoiMjF2ZWsuYnkvMUMiLCJhdWQiOiJNaWNyb3NlcnZpY2VVc2VyIn0.s5HYYpZBF5POynoMYPDM1s10ti4aBc14MTu08i89ok4"
                    },
                    "expiration": {
                      "type": "string",
                      "format": "date-time",
                      "description": "Срок действия токена в UTC",
                      "example": "2021-03-24T13:24:25Z"
                    },
                    "refresh": {
                      "type": "string",
                      "description": "Refresh токен",
                      "example": "PUo3hQD2YR5J2qeDS/EUfep5LAz3uPod6W70m/zmqf0y8ZZThtvKJb6Ft6fqkf/I+Vw7moD8i1i3OEaPhB/PgQ=="
                    },
                    "expiration_refresh": {
                      "type": "string",
                      "format": "date-time",
                      "description": "Срок действия refresh-токена в UTC",
                      "example": "2021-04-08T08:01:51.979274Z"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Неудачная аутентификация",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Подробности",
                      "example": "Invalid token"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/Authenticate/refresh-token": {
      "post": {
        "tags": [
          "Authenticate"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RefreshTokenModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/RefreshTokenModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/RefreshTokenModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Токен валидный, возвращается новый набор, старый токен устаревает",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string",
                      "description": "Токен аутентификации для помещения в заголовок Authorization",
                      "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5AdGVzdC5jb20iLCJqdGkiOiJiZGY1MThlZC05MDg2LTQ2YmMtOGE5My1jNjNmMjgyMjVkMGQiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTYxNjU5MTk1NSwiaXNzIjoiMjF2ZWsuYnkvMUMiLCJhdWQiOiJNaWNyb3NlcnZpY2VVc2VyIn0.s5HYYpZBF5POynoMYPDM1s10ti4aBc14MTu08i89ok4"
                    },
                    "expiration": {
                      "type": "string",
                      "format": "date-time",
                      "description": "Срок действия токена в UTC",
                      "example": "2021-03-24T13:24:25Z"
                    },
                    "refresh": {
                      "type": "string",
                      "description": "Refresh токен",
                      "example": "PUo3hQD2YR5J2qeDS/EUfep5LAz3uPod6W70m/zmqf0y8ZZThtvKJb6Ft6fqkf/I+Vw7moD8i1i3OEaPhB/PgQ=="
                    },
                    "expiration_refresh": {
                      "type": "string",
                      "format": "date-time",
                      "description": "Срок действия refresh-токена в UTC",
                      "example": "2021-04-08T08:01:51.979274Z"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Токен не валидный",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Описание результата",
                      "example": "Invalid token"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/Authenticate/revoke-token": {
      "post": {
        "tags": [
          "Authenticate"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RefreshTokenModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/RefreshTokenModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/RefreshTokenModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Токен отозван",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Описание результата",
                      "example": "Token revoked"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Токен не валидный",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "description": "Описание результата",
                      "example": "Invalid token"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/Authenticate/register": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Authenticate"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/RegisterModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "Status": {
                      "type": "string",
                      "description": "Статус операции",
                      "example": "Success"
                    },
                    "Message": {
                      "type": "string",
                      "description": "Сообщение",
                      "example": "User created successfully!"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Не аутентифицирован"
          },
          "403": {
            "description": "Не хватает ролей у пользователя для данного действия"
          },
          "500": {
            "description": "Ошибка создания пользователя",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "Status": {
                      "type": "string",
                      "description": "Статус операции",
                      "example": "Error"
                    },
                    "Message": {
                      "type": "string",
                      "description": "Сообщение",
                      "example": "User creation failed! Please check user details and try again."
                    },
                    "Description": {
                      "type": "string",
                      "description": "Подробности ошибки",
                      "example": "Слабый пароль"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/Authenticate/delete": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Authenticate"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeleteModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/DeleteModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/DeleteModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "Status": {
                      "type": "string",
                      "description": "Статус операции",
                      "example": "Success"
                    },
                    "Message": {
                      "type": "string",
                      "description": "Сообщение"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Не аутентифицирован"
          },
          "403": {
            "description": "Не хватает ролей у пользователя для данного действия"
          },
          "500": {
            "description": "Ошибка",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "Status": {
                      "type": "string",
                      "description": "Статус операции",
                      "example": "Error"
                    },
                    "Message": {
                      "type": "string",
                      "description": "Сообщение"
                    },
                    "Description": {
                      "type": "string",
                      "description": "Подробности ошибки"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/Authenticate/change-password": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Authenticate"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ChangePasswordModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/ChangePasswordModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/ChangePasswordModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "Status": {
                      "type": "string",
                      "description": "Статус операции",
                      "example": "Success"
                    },
                    "Message": {
                      "type": "string",
                      "description": "Сообщение"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Не аутентифицирован"
          },
          "403": {
            "description": "Не хватает ролей у пользователя для данного действия"
          },
          "500": {
            "description": "Ошибка",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "Status": {
                      "type": "string",
                      "description": "Статус операции",
                      "example": "Error"
                    },
                    "Message": {
                      "type": "string",
                      "description": "Сообщение"
                    },
                    "Description": {
                      "type": "string",
                      "description": "Подробности ошибки"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/Authenticate/modify-roles": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Authenticate"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ModifyRolesModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/ModifyRolesModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/ModifyRolesModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "Status": {
                      "type": "string",
                      "description": "Статус операции",
                      "example": "Success"
                    },
                    "Message": {
                      "type": "string",
                      "description": "Сообщение"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Не аутентифицирован"
          },
          "403": {
            "description": "Не хватает ролей у пользователя для данного действия"
          },
          "500": {
            "description": "Ошибка",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "Status": {
                      "type": "string",
                      "description": "Статус операции",
                      "example": "Error"
                    },
                    "Message": {
                      "type": "string",
                      "description": "Сообщение"
                    },
                    "Description": {
                      "type": "string",
                      "description": "Подробности ошибки"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/Authenticate/available-roles": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Authenticate"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "Status": {
                      "type": "string",
                      "description": "Статус операции",
                      "example": "Success"
                    },
                    "Message": {
                      "type": "string",
                      "description": "Сообщение"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Не аутентифицирован"
          },
          "403": {
            "description": "Не хватает ролей у пользователя для данного действия"
          },
          "500": {
            "description": "Ошибка",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "Status": {
                      "type": "string",
                      "description": "Статус операции",
                      "example": "Error"
                    },
                    "Message": {
                      "type": "string",
                      "description": "Сообщение"
                    },
                    "Description": {
                      "type": "string",
                      "description": "Подробности ошибки"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "payload_interval": {
        "properties": {
          "address_id": {
            "type": "string",
            "description": "Код СОАТО адреса",
            "example": "47175"
          },
          "delivery_type": {
            "type": "string",
            "enum": [
              "self",
              "courier"
            ],
            "description": "Вид доставки - самовывоз (self) или курьер (courier). Если не указан, то считается как доставка",
            "example": "self"
          },
          "pickup_point": {
            "type": "string",
            "description": "Код точки самовывоза",
            "example": "360"
          },
          "floor": {
            "type": "number",
            "description": "Этаж",
            "example": 8
          },
          "payment": {
            "type": "string",
            "enum": [
              "partly_pay",
              "other"
            ],
            "description": "Тип оплаты: partly_pay, other",
            "example": "other"
          },
          "order_date": {
            "type": "string",
            "description": "Дата оформленного заказа",
            "format": "date-time",
            "example": "2021-07-21T16:18:10"
          },
          "order_number": {
            "type": "string",
            "description": "Номер оформленного заказа",
            "example": "100.500.900"
          },
          "x_coordinate": {
            "type": "string",
            "description": "Географическая координата Х",
            "example": 54.303887
          },
          "y_coordinate": {
            "type": "string",
            "description": "Географическая координата Y",
            "example": 26.844061
          },
          "order_items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/orderitem"
            },
            "description": "Список товаров",
            "example": [
              {
                "code": "454100",
                "sales_code": "2770262",
                "quantity": 1
              },
              {
                "code": "424941",
                "quantity": 2
              },
              {
                "code": "609204",
                "quantity": 1
              },
              {
                "code": "6082000",
                "quantity": 6
              }
            ]
          }
        }
      },
      "payload_availabledate": {
        "properties": {
          "city_id": {
            "type": "string",
            "description": "Код города",
            "example": "17030"
          },
          "delivery_types": {
            "type": "array",
            "description": "Вид доставки - самовывоз (self) или курьер (courier)",
            "items": {
              "type": "string",
              "enum": [
                "self",
                "courier"
              ]
            },
            "example": [
              "self",
              "courier"
            ]
          },
          "check_quantity": {
            "type": "boolean",
            "description": "Параметр проверки количества при расчете дат, необязательный - по умолчанию false.",
            "example": true
          },
          "codes": {
            "properties": {
              "code": {
                "type": "string",
                "description": "Артикул номенклатуры"
              },
              "sales_code": {
                "type": "string",
                "description": "Код номенклатуры для уценки (goods_id). Если не уценка, то не отправляется в принципе, либо null"
              },
              "quantity": {
                "type": "number",
                "description": "Количество товаров, нужен при проверке количества"
              },
              "pickup_points": {
                "type": "array",
                "description": "Список кодов ПВЗ",
                "items": {
                  "type": "string"
                }
              }
            },
            "description": "Список артикулов с кодами уценки",
            "example": [
              {
                "code": "789734",
                "sales_code": "2242670",
                "quantity": 1,
                "pickup_points": [
                  "340",
                  "388",
                  "460",
                  "417",
                  "234",
                  "2"
                ]
              },
              {
                "code": "69516",
                "quantity": 10,
                "pickup_points": [
                  "340",
                  "388",
                  "460",
                  "417",
                  "234",
                  "2"
                ]
              }
            ]
          }
        }
      },
      "payload_availabledeliverytypes": {
        "properties": {
          "city_id": {
            "type": "string",
            "description": "Код города",
            "example": "17030"
          },
          "pickup_points": {
            "type": "array",
            "description": "Коды пунктов самовывоза",
            "items": {
              "type": "string",
            },
            "example": [
              "340",
              "388"
            ]
          },
          "items": {
            "properties": {
              "code": {
                "type": "string",
                "description": "Артикул номенклатуры"
              },
              "sales_code": {
                "type": "string",
                "description": "Код номенклатуры для уценки (goods_id). Если не уценка, то не отправляется в принципе, либо null"
              },
              "count": {
                "type": "number",
                "description": "Количество товаров"
              }
            },
            "description": "Список артикулов с кодами уценки и количеством",
            "example": [
              {
                "code": "789734",
                "sales_code": "2242670",
                "quantity": 1
              },
              {
                "code": "69516",
                "quantity": 10
              }
            ]
          }
        }
      },
      "orderitem": {
        "properties": {
          "code": {
            "type": "string",
            "description": "Артикул номенклатуры"
          },
          "sales_code": {
            "type": "string",
            "description": "Код номенклатуры для уценки (goods_id). Если не уценка, то не отправляется в принципе, либо null"
          },
          "quantity": {
            "type": "number",
            "description": "Количество"
          }
        },
        "required": [
          "code",
          "quantity"
        ]
      },
      "LoginModel": {
        "required": [
          "password",
          "username"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "RefreshTokenModel": {
        "required": [
          "refresh_token"
        ],
        "type": "object",
        "properties": {
          "refresh_token": {
            "type": "string",
            "example": "L9kPss+GWOFDFtYWne8l/vinc7545ZtcCVofyL4uhLUiTeYjwUrjwu2nkR09TWOusjxMFUcC/Mm4AMO2KfQVmg=="
          }
        },
        "additionalProperties": false
      },
      "RegisterModel": {
        "required": [
          "email",
          "password",
          "username"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "password": {
            "type": "string"
          },
          "roles": {
            "type": "array",
            "description": "Список ролей для нового пользователя",
            "items": {
              "type": "string"
            },
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "DeleteModel": {
        "required": [
          "username"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "ChangePasswordModel": {
        "required": [
          "username",
          "oldpassword",
          "newpassword"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "oldpassword": {
            "type": "string"
          },
          "newpassword": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "ModifyRolesModel": {
        "required": [
          "username"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "addRoles": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "deleteRoles": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "examples": {
      "interval_courier": {
        "value": {
          "address_id": "47175",
          "delivery_type": "courier",
          "floor": 8,
          "payment": "other",
          "order_items": [
            {
              "code": "789734",
              "sales_code": "2242670",
              "quantity": 1
            },
            {
              "code": "69516",
              "quantity": 10
            }
          ]
        }
      },
      "interval_courier_coords": {
        "value": {
          "delivery_type": "courier",
          "floor": 8,
          "x_coordinate": "54.303887",
          "y_coordinate": "26.844061",
          "order_items": [
            {
              "code": "789734",
              "sales_code": "2242670",
              "quantity": 1
            },
            {
              "code": "69516",
              "quantity": 10
            }
          ]
        }
      },
      "interval_self": {
        "value": {
          "pickup_point": "340",
          "delivery_type": "self",
          "payment": "other",
          "order_items": [
            {
              "code": "789734",
              "sales_code": "2242670",
              "quantity": 1
            },
            {
              "code": "69516",
              "quantity": 10
            }
          ]
        }
      },
      "interval_byOrder": {
        "value": {
          "order_date": "2021-07-21T16:18:10",
          "order_number": "100.500.900"
        }
      },
      "available_delivery_types": {
        "value": {
          "city_id": "17030",
          "pickup_points": [
            "340",
            "388"
          ],
          "items": [
            {
              "code": "789734",
              "sales_code": "2242670",
              "count": 1
            },
            {
              "code": "101937",
              "count": 2
            }
          ]
        }
      },
      "availabledate_basic": {
        "value": {
          "city_id": "17030",
          "delivery_types": [
            "self",
            "courier"
          ],
          "codes": [
            {
              "code": "789734",
              "sales_code": "2242670",
              "pickup_points": [
                "340",
                "388",
                "460",
                "417",
                "234",
                "2"
              ]
            },
            {
              "code": "101937",
              "pickup_points": [
                "340",
                "388",
                "460",
                "417",
                "234",
                "2"
              ]
            },
            {
              "code": "1020938",
              "pickup_points": [
                "340",
                "388",
                "460",
                "417",
                "234",
                "2"
              ]
            }
          ]
        }
      },
      "availabledate_quantity": {
        "value": {
          "city_id": "17030",
          "delivery_types": [
            "self",
            "courier"
          ],
          "check_quantity": true,
          "codes": [
            {
              "code": "789734",
              "sales_code": "2242670",
              "quantity": 6,
              "pickup_points": [
                "340",
                "388",
                "460",
                "417",
                "234",
                "2"
              ]
            },
            {
              "code": "101937",
              "quantity": 5,
              "pickup_points": [
                "340",
                "388",
                "460",
                "417",
                "234",
                "2"
              ]
            },
            {
              "code": "1020938",
              "quantity": 5,
              "pickup_points": [
                "340",
                "388",
                "460",
                "417",
                "234",
                "2"
              ]
            }
          ]
        }
      }
    }
  }
}